[package]
name = "reputation"
version = "0.1.0"
authors = [
    "Vlad Nedelcu <vlad.nedelcu@buidly.com>"
]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.39.2"

[dependencies.common-structs]
path = "../common-structs"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.2"

[dev-dependencies.num-bigint]
version = "0.4.2"

[dev-dependencies.staking-mock]
path = "../staking-mock"