[package]
name = "escrow-factory"
version = "0.1.0"
authors = [
    "Claudiu-Marcel Bruda <claudiu.bruda@elrond.com>",
    "Vlad Nedelcu <vlad.nedelcu@buidly.com>"
]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies]
num-bigint = "0.4.2"

[dependencies.multiversx-sc]
version = "0.39.5"

[dependencies.escrow]
path = "../escrow"

[dependencies.staking-mock]
path = "../staking-mock"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.5"

