[package]
name = "reputation-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.reputation]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
