name: Node.js Base Models NPM publish

on:
  release:
    types: [published]

jobs:
  node-sdk-publish:
    name: Node.js Base Models NPM Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
        name: Install dependencies
      - name: Change Package version
        uses: jossef/action-set-json-field@v2
        with:
          file: ./packages/sdk/typescript/human-protocol-basemodels/package.json
          field: version
          value: ${{ github.event.release.tag_name }}
      - uses: JS-DevTools/npm-publish@v1
        name: Publish
        with:
          package: ./packages/sdk/typescript/human-protocol-basemodels/package.json
          access: public
          token: ${{ secrets.NPM_TOKEN }}
