name: meta-code-verify CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'packages/core/**'
      - 'packages/sdk/typescript/human-protocol-sdk/**'
      - 'packages/apps/dashboard/ui/meta-code-verify/**'
  workflow_dispatch:

jobs:
  meta-code-verify-test:
    name: meta-code-verify Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global yarn && yarn
        name: Install dependencies
      - run: yarn meta-code-verify:test
        name: Run meta-code-verify test
